/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.training.service.app.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Cliente service. Represents a row in the &quot;FacturaService_Cliente&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.training.service.app.model.impl.ClienteModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.training.service.app.model.impl.ClienteImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Cliente
 * @generated
 */
@ProviderType
public interface ClienteModel extends BaseModel<Cliente> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a cliente model instance should use the {@link Cliente} interface instead.
	 */

	/**
	 * Returns the primary key of this cliente.
	 *
	 * @return the primary key of this cliente
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this cliente.
	 *
	 * @param primaryKey the primary key of this cliente
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the cliente ID of this cliente.
	 *
	 * @return the cliente ID of this cliente
	 */
	public long getClienteId();

	/**
	 * Sets the cliente ID of this cliente.
	 *
	 * @param clienteId the cliente ID of this cliente
	 */
	public void setClienteId(long clienteId);

	/**
	 * Returns the name of this cliente.
	 *
	 * @return the name of this cliente
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this cliente.
	 *
	 * @param name the name of this cliente
	 */
	public void setName(String name);

	/**
	 * Returns the cell of this cliente.
	 *
	 * @return the cell of this cliente
	 */
	@AutoEscape
	public String getCell();

	/**
	 * Sets the cell of this cliente.
	 *
	 * @param cell the cell of this cliente
	 */
	public void setCell(String cell);

	@Override
	public Cliente cloneWithOriginalValues();

}