/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.training.service.app.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Factura service. Represents a row in the &quot;FacturaService_Factura&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.training.service.app.model.impl.FacturaModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.training.service.app.model.impl.FacturaImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Factura
 * @generated
 */
@ProviderType
public interface FacturaModel extends BaseModel<Factura> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a factura model instance should use the {@link Factura} interface instead.
	 */

	/**
	 * Returns the primary key of this factura.
	 *
	 * @return the primary key of this factura
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this factura.
	 *
	 * @param primaryKey the primary key of this factura
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the factura ID of this factura.
	 *
	 * @return the factura ID of this factura
	 */
	public long getFacturaId();

	/**
	 * Sets the factura ID of this factura.
	 *
	 * @param facturaId the factura ID of this factura
	 */
	public void setFacturaId(long facturaId);

	/**
	 * Returns the total of this factura.
	 *
	 * @return the total of this factura
	 */
	@AutoEscape
	public String getTotal();

	/**
	 * Sets the total of this factura.
	 *
	 * @param total the total of this factura
	 */
	public void setTotal(String total);

	/**
	 * Returns the cliente ID of this factura.
	 *
	 * @return the cliente ID of this factura
	 */
	public long getClienteId();

	/**
	 * Sets the cliente ID of this factura.
	 *
	 * @param clienteId the cliente ID of this factura
	 */
	public void setClienteId(long clienteId);

	@Override
	public Factura cloneWithOriginalValues();

}