/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.training.service.app.model;

import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ItemFactura service. Represents a row in the &quot;FacturaService_ItemFactura&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.training.service.app.model.impl.ItemFacturaModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.training.service.app.model.impl.ItemFacturaImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ItemFactura
 * @generated
 */
@ProviderType
public interface ItemFacturaModel extends BaseModel<ItemFactura> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a item factura model instance should use the {@link ItemFactura} interface instead.
	 */

	/**
	 * Returns the primary key of this item factura.
	 *
	 * @return the primary key of this item factura
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this item factura.
	 *
	 * @param primaryKey the primary key of this item factura
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the item factura ID of this item factura.
	 *
	 * @return the item factura ID of this item factura
	 */
	public long getItemFacturaId();

	/**
	 * Sets the item factura ID of this item factura.
	 *
	 * @param itemFacturaId the item factura ID of this item factura
	 */
	public void setItemFacturaId(long itemFacturaId);

	/**
	 * Returns the cantidad prod of this item factura.
	 *
	 * @return the cantidad prod of this item factura
	 */
	public long getCantidadProd();

	/**
	 * Sets the cantidad prod of this item factura.
	 *
	 * @param cantidadProd the cantidad prod of this item factura
	 */
	public void setCantidadProd(long cantidadProd);

	/**
	 * Returns the factura ID of this item factura.
	 *
	 * @return the factura ID of this item factura
	 */
	public long getFacturaId();

	/**
	 * Sets the factura ID of this item factura.
	 *
	 * @param facturaId the factura ID of this item factura
	 */
	public void setFacturaId(long facturaId);

	/**
	 * Returns the producto ID of this item factura.
	 *
	 * @return the producto ID of this item factura
	 */
	public long getProductoId();

	/**
	 * Sets the producto ID of this item factura.
	 *
	 * @param productoId the producto ID of this item factura
	 */
	public void setProductoId(long productoId);

	@Override
	public ItemFactura cloneWithOriginalValues();

}