/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.training.service.app.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.training.service.app.model.ItemFactura;
import com.liferay.training.service.app.model.ItemFacturaModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ItemFactura service. Represents a row in the &quot;FacturaService_ItemFactura&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ItemFacturaModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ItemFacturaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ItemFacturaImpl
 * @generated
 */
@JSON(strict = true)
public class ItemFacturaModelImpl
	extends BaseModelImpl<ItemFactura> implements ItemFacturaModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a item factura model instance should use the <code>ItemFactura</code> interface instead.
	 */
	public static final String TABLE_NAME = "FacturaService_ItemFactura";

	public static final Object[][] TABLE_COLUMNS = {
		{"itemFacturaId", Types.BIGINT}, {"cantidadProd", Types.BIGINT},
		{"facturaId", Types.BIGINT}, {"productoId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("itemFacturaId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("cantidadProd", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("facturaId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("productoId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table FacturaService_ItemFactura (itemFacturaId LONG not null primary key,cantidadProd LONG,facturaId LONG,productoId LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table FacturaService_ItemFactura";

	public static final String ORDER_BY_JPQL =
		" ORDER BY itemFactura.itemFacturaId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY FacturaService_ItemFactura.itemFacturaId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long FACTURAID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PRODUCTOID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ITEMFACTURAID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public ItemFacturaModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _itemFacturaId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setItemFacturaId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _itemFacturaId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ItemFactura.class;
	}

	@Override
	public String getModelClassName() {
		return ItemFactura.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ItemFactura, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ItemFactura, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ItemFactura, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ItemFactura)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ItemFactura, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ItemFactura, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ItemFactura)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ItemFactura, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ItemFactura, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<ItemFactura, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<ItemFactura, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<ItemFactura, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<ItemFactura, Object>>();
		Map<String, BiConsumer<ItemFactura, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<ItemFactura, ?>>();

		attributeGetterFunctions.put(
			"itemFacturaId", ItemFactura::getItemFacturaId);
		attributeSetterBiConsumers.put(
			"itemFacturaId",
			(BiConsumer<ItemFactura, Long>)ItemFactura::setItemFacturaId);
		attributeGetterFunctions.put(
			"cantidadProd", ItemFactura::getCantidadProd);
		attributeSetterBiConsumers.put(
			"cantidadProd",
			(BiConsumer<ItemFactura, Long>)ItemFactura::setCantidadProd);
		attributeGetterFunctions.put("facturaId", ItemFactura::getFacturaId);
		attributeSetterBiConsumers.put(
			"facturaId",
			(BiConsumer<ItemFactura, Long>)ItemFactura::setFacturaId);
		attributeGetterFunctions.put("productoId", ItemFactura::getProductoId);
		attributeSetterBiConsumers.put(
			"productoId",
			(BiConsumer<ItemFactura, Long>)ItemFactura::setProductoId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getItemFacturaId() {
		return _itemFacturaId;
	}

	@Override
	public void setItemFacturaId(long itemFacturaId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_itemFacturaId = itemFacturaId;
	}

	@JSON
	@Override
	public long getCantidadProd() {
		return _cantidadProd;
	}

	@Override
	public void setCantidadProd(long cantidadProd) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_cantidadProd = cantidadProd;
	}

	@JSON
	@Override
	public long getFacturaId() {
		return _facturaId;
	}

	@Override
	public void setFacturaId(long facturaId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_facturaId = facturaId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalFacturaId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("facturaId"));
	}

	@JSON
	@Override
	public long getProductoId() {
		return _productoId;
	}

	@Override
	public void setProductoId(long productoId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_productoId = productoId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalProductoId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("productoId"));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, ItemFactura.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ItemFactura toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ItemFactura>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ItemFacturaImpl itemFacturaImpl = new ItemFacturaImpl();

		itemFacturaImpl.setItemFacturaId(getItemFacturaId());
		itemFacturaImpl.setCantidadProd(getCantidadProd());
		itemFacturaImpl.setFacturaId(getFacturaId());
		itemFacturaImpl.setProductoId(getProductoId());

		itemFacturaImpl.resetOriginalValues();

		return itemFacturaImpl;
	}

	@Override
	public ItemFactura cloneWithOriginalValues() {
		ItemFacturaImpl itemFacturaImpl = new ItemFacturaImpl();

		itemFacturaImpl.setItemFacturaId(
			this.<Long>getColumnOriginalValue("itemFacturaId"));
		itemFacturaImpl.setCantidadProd(
			this.<Long>getColumnOriginalValue("cantidadProd"));
		itemFacturaImpl.setFacturaId(
			this.<Long>getColumnOriginalValue("facturaId"));
		itemFacturaImpl.setProductoId(
			this.<Long>getColumnOriginalValue("productoId"));

		return itemFacturaImpl;
	}

	@Override
	public int compareTo(ItemFactura itemFactura) {
		long primaryKey = itemFactura.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ItemFactura)) {
			return false;
		}

		ItemFactura itemFactura = (ItemFactura)object;

		long primaryKey = itemFactura.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ItemFactura> toCacheModel() {
		ItemFacturaCacheModel itemFacturaCacheModel =
			new ItemFacturaCacheModel();

		itemFacturaCacheModel.itemFacturaId = getItemFacturaId();

		itemFacturaCacheModel.cantidadProd = getCantidadProd();

		itemFacturaCacheModel.facturaId = getFacturaId();

		itemFacturaCacheModel.productoId = getProductoId();

		return itemFacturaCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ItemFactura, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ItemFactura, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ItemFactura, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((ItemFactura)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<ItemFactura, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<ItemFactura, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ItemFactura, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((ItemFactura)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ItemFactura>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					ItemFactura.class, ModelWrapper.class);

	}

	private long _itemFacturaId;
	private long _cantidadProd;
	private long _facturaId;
	private long _productoId;

	public <T> T getColumnValue(String columnName) {
		Function<ItemFactura, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((ItemFactura)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("itemFacturaId", _itemFacturaId);
		_columnOriginalValues.put("cantidadProd", _cantidadProd);
		_columnOriginalValues.put("facturaId", _facturaId);
		_columnOriginalValues.put("productoId", _productoId);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("itemFacturaId", 1L);

		columnBitmasks.put("cantidadProd", 2L);

		columnBitmasks.put("facturaId", 4L);

		columnBitmasks.put("productoId", 8L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private ItemFactura _escapedModel;

}